apiVersion: apps/v1
kind: Deployment
metadata:
  name: expapp-deployment
  labels:
    app: expapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expapp
  template:
    metadata:
      labels:
        app: expapp
    spec:
      containers:
        - name: expapp
          image: youcef26/expimage:17
          ports:
            - containerPort: 3000
